
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javafx.embed.swing.JFXPanel;

public class MainFrame extends javax.swing.JFrame {

    DB_MAN DBM = new DB_MAN();
    
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup = new javax.swing.JFrame();
        txtId = new javax.swing.JTextField();
        txtPasswd = new javax.swing.JPasswordField();
        txtPasswdConfirm = new javax.swing.JPasswordField();
        lblId1 = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        lblPasswdConfirm = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegisterCheck = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        signIn_popup = new javax.swing.JDialog();
        signin_fail_1 = new javax.swing.JLabel();
        personalInfo1 = new PersonalInfo();
        signup_popup = new javax.swing.JDialog();
        jIdField1 = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        lblLogIn = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        lblId1.setText("아이디");

        lblPasswd.setText("비밀번호");

        lblPasswdConfirm.setText("비밀번호 확인");

        btnCheck.setText("중복확인");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setText("회원가입");

        btnRegisterCheck.setText("회원가입");
        btnRegisterCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCheckActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupLayout = new javax.swing.GroupLayout(signup.getContentPane());
        signup.getContentPane().setLayout(signupLayout);
        signupLayout.setHorizontalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(signupLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasswd)
                    .addComponent(lblId1)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPasswd)
                            .addComponent(txtId)
                            .addComponent(lblPasswdConfirm)
                            .addComponent(txtPasswdConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(signupLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnRegisterCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupLayout.setVerticalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblId1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addGap(18, 18, 18)
                .addComponent(lblPasswd)
                .addGap(10, 10, 10)
                .addComponent(txtPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswdConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswdConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(btnRegisterCheck)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        signIn_popup.setModal(true);

        signin_fail_1.setText("없는 아이디 또는 틀린 비번");

        javax.swing.GroupLayout signIn_popupLayout = new javax.swing.GroupLayout(signIn_popup.getContentPane());
        signIn_popup.getContentPane().setLayout(signIn_popupLayout);
        signIn_popupLayout.setHorizontalGroup(
            signIn_popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signIn_popupLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(signin_fail_1)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        signIn_popupLayout.setVerticalGroup(
            signIn_popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signIn_popupLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(signin_fail_1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout signup_popupLayout = new javax.swing.GroupLayout(signup_popup.getContentPane());
        signup_popup.getContentPane().setLayout(signup_popupLayout);
        signup_popupLayout.setHorizontalGroup(
            signup_popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        signup_popupLayout.setVerticalGroup(
            signup_popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblId.setText("아이디");

        lblPw.setText("비밀번호");

        btnSignUp.setText("회원가입");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblLogIn.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        lblLogIn.setText("로그인");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignUp)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPw)
                            .addComponent(lblId)
                            .addComponent(jIdField1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnLogin))
                            .addComponent(jPasswordField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblLogIn)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblLogIn)
                .addGap(43, 43, 43)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLogin)
                .addGap(58, 58, 58)
                .addComponent(btnSignUp)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if(personalInfo1.checkDuplication(txtId.getText())){
            JOptionPane.showMessageDialog(signup_popup, "사용할 수 없는 아이디입니다.", "중복확인", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(signup_popup, "사용 가능한 아이디입니다.", "중복확인", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnRegisterCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCheckActionPerformed
        if(personalInfo1.checkSignUp(txtPasswd.getText(), txtPasswdConfirm.getText())){
            JOptionPane.showMessageDialog(signIn_popup, "회원가입 성공.", "회원가입", JOptionPane.INFORMATION_MESSAGE);
            signup.dispose();
        } else{
            JOptionPane.showMessageDialog(signIn_popup, "비밀번호가 올바르지않습니다..", "회원가입", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterCheckActionPerformed
    
    // 회원가입 버튼 누를시 창 이동
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        signup.setVisible(true);
        signup.setLocation(800, 300);
        signup.setSize(400, 600);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reCAPTCHA captcha = new reCAPTCHA();
        JFXPanel captchaPanel = captcha.createCaptchaWindow();
        
        add(captchaPanel);
        setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // 로그인 버튼을 누르면 데이터베이스에 저장되어 있는 id와 비교하여 판단하고 비밀번호를 가져와 대조
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(personalInfo1.checkIDPW(jIdField1.getText(), jPasswordField1.getText()) == true){
            SubFrame frame = new SubFrame();   // SubFrame 실행
            frame.updateID(personalInfo1.getId());
            frame.setVisible(true);
            frame.setLocation(800, 300);
            dispose();    // 현재 창 종료
        }
        else{
            JOptionPane.showMessageDialog(signIn_popup, "존재하지않는 회원아이디이거나 틀린 비밀번호입니다.", "로그인실패", JOptionPane.INFORMATION_MESSAGE);   // 로그인 실패 창
        }
    }//GEN-LAST:event_btnLoginActionPerformed
                                 

    // 아이디 입력 창을 누르면 비워지게 설정
    private void jIdField1MouseClicked(java.awt.event.MouseEvent evt) {                                       
        jIdField1.setText(null);
    }                                      
    
    // 비밀번호 입력 창을 누르면 비워지게 설정
    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {                                             
        jPasswordField1.setText(null);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegisterCheck;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jIdField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblPasswdConfirm;
    private javax.swing.JLabel lblPw;
    private PersonalInfo personalInfo1;
    private javax.swing.JDialog signIn_popup;
    private javax.swing.JLabel signin_fail_1;
    private javax.swing.JFrame signup;
    private javax.swing.JDialog signup_popup;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtPasswd;
    private javax.swing.JPasswordField txtPasswdConfirm;
    // End of variables declaration//GEN-END:variables
}
