
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khg09
 */

public class SubFrame extends javax.swing.JFrame {
    
    private String id = null;
    /**
     * Creates new form SubFrame
     */
    public SubFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jManageFrame = new javax.swing.JFrame();
        lblManage = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jProductField1 = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        jComboCategory1 = new javax.swing.JComboBox<>();
        lblPrice = new javax.swing.JLabel();
        jPriceField1 = new javax.swing.JTextField();
        lblExpired = new javax.swing.JLabel();
        jExpiredField1 = new javax.swing.JTextField();
        lblStart = new javax.swing.JLabel();
        jStartField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jStockFrame = new javax.swing.JFrame();
        lblStock = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLogFrame = new javax.swing.JFrame();
        jComboYear2 = new javax.swing.JComboBox<>();
        jComboMonth2 = new javax.swing.JComboBox<>();
        jComboDay2 = new javax.swing.JComboBox<>();
        lblYear2 = new javax.swing.JLabel();
        lblMonth2 = new javax.swing.JLabel();
        lblDay2 = new javax.swing.JLabel();
        jComboYear1 = new javax.swing.JComboBox<>();
        lblYear1 = new javax.swing.JLabel();
        jComboMonth1 = new javax.swing.JComboBox<>();
        lblMonth1 = new javax.swing.JLabel();
        jComboDay1 = new javax.swing.JComboBox<>();
        lblDay1 = new javax.swing.JLabel();
        justLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboType1 = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnExit2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        personalInfo1 = new PersonalInfo();
        popup = new javax.swing.JDialog();
        btnManage = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        lblManage.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lblManage.setText("상품관리");

        lblProduct.setText("상품명");

        lblCategory.setText("카테고리");

        jComboCategory1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "식품", "문구", "전자제품", "의류", "귀금속" }));

        lblPrice.setText("가격");

        lblExpired.setText("유통기한");

        lblStart.setText("제조일자");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "상품명", "카테고리", "가격", "유통기한", "제조일자"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnInsert.setText("등록");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("수정");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("삭제");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("나가기");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jManageFrame.setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout jManageFrameLayout = new javax.swing.GroupLayout(jManageFrame.getContentPane());
        jManageFrame.getContentPane().setLayout(jManageFrameLayout);
        jManageFrameLayout.setHorizontalGroup(
            jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jManageFrameLayout.createSequentialGroup()
                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jManageFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate)))
                    .addGroup(jManageFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete)))
                .addGap(58, 58, 58))
            .addGroup(jManageFrameLayout.createSequentialGroup()
                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jManageFrameLayout.createSequentialGroup()
                        .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jManageFrameLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jStartField1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addGroup(jManageFrameLayout.createSequentialGroup()
                                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jManageFrameLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblProduct))
                                    .addGroup(jManageFrameLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lblPrice)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPriceField1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jProductField1))))
                        .addGap(44, 44, 44)
                        .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jManageFrameLayout.createSequentialGroup()
                                .addComponent(lblCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jManageFrameLayout.createSequentialGroup()
                                .addComponent(lblExpired)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExpiredField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblManage)))
                    .addGroup(jManageFrameLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jManageFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(38, 38, 38))
        );
        jManageFrameLayout.setVerticalGroup(
            jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jManageFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblManage)
                .addGap(27, 27, 27)
                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct)
                    .addComponent(jProductField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory)
                    .addComponent(jComboCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(jPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(jManageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStart)
                    .addComponent(lblExpired)
                    .addComponent(jExpiredField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStartField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jStockFrame.setPreferredSize(new java.awt.Dimension(775, 610));

        lblStock.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lblStock.setText("재고 관리");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jStockFrame.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout jStockFrameLayout = new javax.swing.GroupLayout(jStockFrame.getContentPane());
        jStockFrame.getContentPane().setLayout(jStockFrameLayout);
        jStockFrameLayout.setHorizontalGroup(
            jStockFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStockFrameLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(lblStock)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jStockFrameLayout.setVerticalGroup(
            jStockFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStockFrameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblStock)
                .addContainerGap(536, Short.MAX_VALUE))
        );

        jComboYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", " ", " ", " " }));

        jComboMonth2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboDay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lblYear2.setText("년");

        lblMonth2.setText("월");

        lblDay2.setText("일까지");

        jComboYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", " ", " ", " " }));

        lblYear1.setText("년");

        jComboMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblMonth1.setText("월");

        jComboDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lblDay1.setText("일부터");

        justLabel.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        justLabel.setText("~");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "상품명", "수량", "날짜", "입출&출고 여부"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전체보기", "입고", "출고" }));

        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnExit2.setText("나가기");
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jLogFrame.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jLogFrameLayout = new javax.swing.GroupLayout(jLogFrame.getContentPane());
        jLogFrame.getContentPane().setLayout(jLogFrameLayout);
        jLogFrameLayout.setHorizontalGroup(
            jLogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYear1)
                .addGap(12, 12, 12)
                .addComponent(jComboMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonth1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(justLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYear2)
                .addGap(12, 12, 12)
                .addComponent(jComboMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonth2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDay2)
                .addGap(47, 47, 47))
            .addGroup(jLogFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jLogFrameLayout.createSequentialGroup()
                            .addComponent(btnExit2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch)
                            .addGap(18, 18, 18))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLogFrameLayout.setVerticalGroup(
            jLogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear1)
                    .addComponent(lblMonth1)
                    .addComponent(lblDay1)
                    .addComponent(jComboYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear2)
                    .addComponent(lblMonth2)
                    .addComponent(lblDay2)
                    .addComponent(justLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLogFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnExit2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup.getContentPane());
        popup.getContentPane().setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnManage.setText("상품관리");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        btnStock.setText("재고관리");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnSetting.setText("설정");

        btnLog.setText("입고&출고 기록확인");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("상품 재고관리 시스템");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblTitle)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addComponent(btnSetting)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 기록 조회 버튼
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        DB_MAN DBM = new DB_MAN();
        String strQuery = null;
        String from = null;
        String to = null;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // 테이블 모델 가져오기
        model.setRowCount(0); // 기존 데이터를 모두 삭제
        
        from = jComboYear1.getSelectedItem() + "-" + jComboMonth1.getSelectedItem() + "-" + jComboDay1.getSelectedItem();
        to = jComboYear2.getSelectedItem() + "-" + jComboMonth2.getSelectedItem() + "-" + jComboDay2.getSelectedItem();
        
        if (jComboType1.getSelectedItem().equals("전체보기")) {
            strQuery = "select * from " + id + ".log where log_day between '" + from + "' and '" + to + "'";
        } else if (jComboType1.getSelectedItem().equals("입고")) {
            strQuery = "select * from " + id + ".log where io = '입고' and log_day between '" + from + "' and '" + to + "'";
        } else if (jComboType1.getSelectedItem().equals("출고")) {
            strQuery = "select * from " + id + ".log where io = '출고' and log_day between '" + from + "' and '" + to + "'";
        }
            
        try{
            DBM.dbOpen();
            DBM.rs = DBM.stmt.executeQuery(strQuery);

            while(DBM.rs.next()){
                Object[] rowData = new Object[4];
                rowData[0] = DBM.rs.getString(1);  // 상품명
                rowData[1] = DBM.rs.getString(2);  // 수량
                rowData[2] = DBM.rs.getString(3);  // 날짜
                rowData[3] = DBM.rs.getString(4);  // 입출고 여부
                model.addRow(rowData);  // 테이블에 행 추가
            }
            DBM.dbClose();
        } catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }          
    }//GEN-LAST:event_btnSearchActionPerformed

    // 입고&출고 버튼 누르면 창 이동
    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        jLogFrame.setVisible(true);
        jLogFrame.setLocation(800, 300);
        jLogFrame.setSize(775, 610);
    }//GEN-LAST:event_btnLogActionPerformed

    // 상품관리 버튼 누르면 창 이동
    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        jManageFrame.setVisible(true);
        jManageFrame.setLocation(800, 300);
        jManageFrame.setSize(624, 624);
        table2Reload();
    }//GEN-LAST:event_btnManageActionPerformed

    // 상품관리에서 상품 등록
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        DB_MAN DBM = new DB_MAN();
        String strQuery = "insert into " + id + ".manage values('" + jProductField1.getText() + "', '" + jComboCategory1.getSelectedItem() + "', '" + jPriceField1.getText() + "', '" + jStartField1.getText() + "', '" + jExpiredField1.getText() + "')";  
        
        try{
            DBM.dbOpen();
            DBM.stmt.executeUpdate(strQuery);
            table2Reload();
            DBM.dbClose();
        } catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
            JOptionPane.showMessageDialog(popup, "상품명은 필수적으로 작성해주세요.", "오류발생", JOptionPane.INFORMATION_MESSAGE);
        }
        
        jProductField1.setText(null);
        jPriceField1.setText(null);
        jStartField1.setText(null);
        jExpiredField1.setText(null);
    }//GEN-LAST:event_btnInsertActionPerformed
    
    // 상품관리에서 상품 변경
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DB_MAN DBM = new DB_MAN();
        String strQuery = "update " + id + ".manage set category = '" + jComboCategory1.getSelectedItem() + "', price = '" + jPriceField1.getText() + "', startdate = '" + jStartField1.getText() + "', expireddate = '" + jExpiredField1.getText() + "' where product = '" + jProductField1.getText() + "'";  
        
        try{
            DBM.dbOpen();
            DBM.stmt.executeUpdate(strQuery);
            table2Reload();
            DBM.dbClose();
        } catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        jProductField1.setText(null);
        jPriceField1.setText(null);
        jStartField1.setText(null);
        jExpiredField1.setText(null);
    }//GEN-LAST:event_btnUpdateActionPerformed

    // 상품관리에서 상품 삭제
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DB_MAN DBM = new DB_MAN();
        String strQuery = "delete from " + id + ".manage where product = '" + jTable2.getValueAt(jTable2.getSelectedRow(), 0)+ "'";
        
        try{
            DBM.dbOpen();
            DBM.stmt.executeUpdate(strQuery);
            table2Reload();
            DBM.dbClose();
        } catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
        jProductField1.setText(null);
        jPriceField1.setText(null);
        jStartField1.setText(null);
        jExpiredField1.setText(null);
    }//GEN-LAST:event_btnDeleteActionPerformed

    // 상품관리에서 뒤로가기 
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        jManageFrame.dispose();
    }//GEN-LAST:event_btnExitActionPerformed
    
    // 입고&출고 기록에서 나가기
    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        jLogFrame.dispose();
    }//GEN-LAST:event_btnExit2ActionPerformed

    // 재고관리 버튼 누르면 창 이동
    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        jStockFrame.setVisible(true);
        jStockFrame.setLocation(800, 300);
        jStockFrame.setSize(775, 610);
    }//GEN-LAST:event_btnStockActionPerformed

    // 상품관리 테이블 리로드
    public void table2Reload(){
        DB_MAN DBM = new DB_MAN();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); // 테이블 모델 가져오기
        model.setRowCount(0); // 기존 데이터를 모두 삭제
        String strQuery = "select * from " + id + ".manage";
        
        try{
            DBM.dbOpen();
            DBM.rs = DBM.stmt.executeQuery(strQuery);

            while(DBM.rs.next()){
                Object[] rowData = new Object[5];
                rowData[0] = DBM.rs.getString(1);  // 상품명
                rowData[1] = DBM.rs.getString(2);  // 카테고리
                rowData[2] = DBM.rs.getString(3);  // 가격
                rowData[3] = DBM.rs.getString(4);  // 유통기간
                rowData[4] = DBM.rs.getString(5);  // 제조일자
                model.addRow(rowData);  // 테이블에 행 추가
            }
            DBM.dbClose();
        } catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }
    
    public void updateID(String id){
        this.id = id;
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboCategory1;
    private javax.swing.JComboBox<String> jComboDay1;
    private javax.swing.JComboBox<String> jComboDay2;
    private javax.swing.JComboBox<String> jComboMonth1;
    private javax.swing.JComboBox<String> jComboMonth2;
    private javax.swing.JComboBox<String> jComboType1;
    private javax.swing.JComboBox<String> jComboYear1;
    private javax.swing.JComboBox<String> jComboYear2;
    private javax.swing.JTextField jExpiredField1;
    private javax.swing.JFrame jLogFrame;
    private javax.swing.JFrame jManageFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JTextField jPriceField1;
    private javax.swing.JTextField jProductField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jStartField1;
    private javax.swing.JFrame jStockFrame;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel justLabel;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDay1;
    private javax.swing.JLabel lblDay2;
    private javax.swing.JLabel lblExpired;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblMonth1;
    private javax.swing.JLabel lblMonth2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear1;
    private javax.swing.JLabel lblYear2;
    private PersonalInfo personalInfo1;
    private javax.swing.JDialog popup;
    // End of variables declaration//GEN-END:variables
}
